name: 'Build & Release Mock Broy'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions:
      contents: write
      
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and Release
        run: npm run build
        env:
          # Token ini sekarang akan digunakan oleh Electron Builder untuk membuat rilis
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}